[workspace]
members = ["crates/*", "tests"]
resolver = "3"

[workspace.package]
version = "0.1.4"
description = "A dependency injection framework for Rust"
authors = ["Hermanest"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/Hermanest/deorbit"
keywords = ["di", "di-container", "injection", "runtime", "macros"]